export const checkboxOptions = ['Expected Goals per 90', 
'Non-penalty xG per 90', 
'Goals per 90',
'Non-penalty Goals per 90',
'Goals minus xG',
'Goals minus Non-penalty xG',
'Non-penalty xG per Shot',
'Shots per 90',
'Shots on Target per 90',
'Avg. Shot Distance from Goal',
'Expected Assists per 90',
'Assists per 90',
'Key Passes per 90',
'Goal Creating Actions per 90',
'Goal Creating Actions from Live Balls per 90',
'Goal Creating Actions from Dead Balls per 90',
'Goal Creating Actions from Take-ons per 90',
'Shot Creating Actions per 90',
'Shot Creating Actions from Live Balls per 90',
'Shot Creating Actions from Dead Balls per 90',
'Shot Creating Actions from Take-ons per 90',
'Progressive Carries per 90',
'Carries per 90',
'Carries into Final 3rd per 90',
'Carries into Penalty Area per 90',
'Progressive Carrying Distance per 90',
'Progressive Passes per 90',
'Through Balls per 90',
'Progressive Passes Received per 90',
'Passes Received per 90',
'Passes into Final 3rd per 90',
'Passes into Penalty Area per 90',
'Touches per 90',
'Touches in Attacking Penalty Area per 90',
'Touches in Attacking 3rd per 90',
'Touches in Middle 3rd per 90',
'Touches in Defensive 3rd per 90',
'Ball Recoveries per 90',
'Successful Take-ons per 90',
'Take-ons Attempted per 90',
'Fouls Drawn per 90',
'Fouls Committed per 90',
'Times dispossessed per 90',
'Miscontrols per 90',
'Errors per 90',
'Passes Attempted per 90',
'Passes Completed per 90',
'Long Passes Attempted per 90',
'Long Passes Completed per 90',
'Medium Passes Attempted per 90',
'Medium Passes Completed per 90',
'Short Passes Attempted per 90',
'Short Passes Completed per 90',
'Crosses per 90',
'Switches per 90',
'Passes Offside per 90',
'Tackles and Interceptions per 90',
'Tackles Attempted per 90',
'Tackles Won per 90',
'Tackles in Attacking 3rd per 90',
'Tackles in Middle 3rd per 90',
'Tackles in Defensive 3rd per 90',
'Interceptions per 90',
'Dribblers Challenged per 90',
'Dribblers Tackled per 90',
'Challenges Lost per 90',
'Aerials Won per 90',
'Aerials Lost per 90',
'Blocks per 90'
];